DO $$ BEGIN
  ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_CONVERSATION_ESCALATED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_FOLLOWUP_DRAFT_GENERATED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "aiExchangeCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "AiEmailDraft" ADD COLUMN IF NOT EXISTS "draftKind" TEXT NOT NULL DEFAULT 'ACKNOWLEDGEMENT';
ALTER TABLE "AiEmailDraft" ADD COLUMN IF NOT EXISTS "exchangeTurn" INTEGER;
