ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "glpiTicketsSyncIntervalSeconds" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "emailSyncIntervalSeconds" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "aiModelsSyncIntervalHours" INTEGER NOT NULL DEFAULT 24;
