ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "receiveDraftAlerts" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "AiEmailDraft" ADD COLUMN IF NOT EXISTS "reminderCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AiEmailDraft" ADD COLUMN IF NOT EXISTS "lastReminderAt" TIMESTAMP(3);

ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "draftReminderEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "SystemSettings" ADD COLUMN IF NOT EXISTS "draftReminderDelayMinutes" INTEGER NOT NULL DEFAULT 30;
