ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "splitCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "firstOpenedAt" TIMESTAMP(3);

ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'SPLIT_NEW_ISSUE';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'CREATED_FROM_SPLIT';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_LOW_CONFIDENCE_CLOSE_SKIPPED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_LOW_CONFIDENCE_REOPEN_SKIPPED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_AUTO_REPLY_IGNORED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_LIFETIME_EXCEEDED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_SPLIT_LIMIT_REACHED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'NEEDS_HUMAN_REVIEW';
