/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#dce9ff',
        'on-secondary-container': '#004666',
        'tertiary-container': '#a44100',
        'on-background': '#0b1c30',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#351000',
        'surface-bright': '#f8f9ff',
        'primary-fixed': '#e2dfff',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eaf1ff',
        background: '#f8f9ff',
        'on-surface': '#0b1c30',
        'inverse-primary': '#c3c0ff',
        secondary: '#006591',
        'secondary-container': '#39b8fd',
        'primary-container': '#4f46e5',
        'primary-fixed-dim': '#c3c0ff',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary-fixed-variant': '#7b2f00',
        'surface-container': '#e5eeff',
        'surface-tint': '#4d44e3',
        surface: '#f8f9ff',
        'on-primary-container': '#dad7ff',
        'on-secondary-fixed': '#001e2f',
        'on-tertiary-container': '#ffd2be',
        'on-primary-fixed': '#0f0069',
        'secondary-fixed': '#c9e6ff',
        'surface-container-low': '#eff4ff',
        'secondary-fixed-dim': '#89ceff',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#464555',
        'inverse-surface': '#213145',
        'surface-variant': '#d3e4fe',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'tertiary-fixed-dim': '#ffb695',
        'surface-dim': '#cbdbf5',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#004c6e',
        primary: '#3525cd',
        'on-primary-fixed-variant': '#3323cc',
        tertiary: '#7e3000',
        error: '#ba1a1a',
        'tertiary-fixed': '#ffdbcc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        'container-margin': '2rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['Inter'],
        'mono-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'mono-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
