/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Colors SEVEN-T
        gold: {
          300: '#fde68a',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
        },
        space: {
          950: '#0a0c10',
          900: '#12141c',
          800: '#1a1d27',
          700: '#2d313f',
          600: '#3f4456',
        },

        // ── Mode clair (valeurs par défaut) ──────────────────────────────────
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-background': 'var(--color-on-background)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'surface-bright': 'var(--color-surface-bright)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-error-container': 'var(--color-on-error-container)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        background: 'var(--color-background)',
        'on-surface': 'var(--color-on-surface)',
        'inverse-primary': 'var(--color-inverse-primary)',
        secondary: 'var(--color-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'primary-container': 'var(--color-primary-container)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-container': 'var(--color-surface-container)',
        'surface-tint': 'var(--color-surface-tint)',
        surface: 'var(--color-surface)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-primary': 'var(--color-on-primary)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        primary: 'var(--color-primary)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        tertiary: 'var(--color-tertiary)',
        error: 'var(--color-error)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        
        // ── Shadcn-compatible colors → mapped to M3 tokens ─────────────────────
        foreground: 'var(--color-on-surface)',
        'primary-foreground': 'var(--color-on-primary)',
        'secondary-foreground': 'var(--color-on-surface)',
        border: 'var(--color-outline-variant)',
        input: 'var(--color-outline-variant)',
        ring: 'var(--color-primary)',
        card: {
          DEFAULT: 'var(--color-surface-container-lowest)',
          foreground: 'var(--color-on-surface)',
        },
        popover: {
          DEFAULT: 'var(--color-surface-container-lowest)',
          foreground: 'var(--color-on-surface)',
        },
        muted: {
          DEFAULT: 'var(--color-surface-container-low)',
          foreground: 'var(--color-on-surface-variant)',
        },
        accent: {
          DEFAULT: 'var(--color-surface-container-low)',
          foreground: 'var(--color-on-surface)',
        },
        destructive: {
          DEFAULT: 'var(--color-error)',
          foreground: 'var(--color-on-error)',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        'container-margin': '2rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer', 'system-ui', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'body-sm': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'body-md': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'headline-lg': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'mono-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'headline-md': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'body-lg': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
        'label-md': ['"Plus Jakarta Sans"', '"Inter"', 'Gilmer'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-xs': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'mono-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'mono-xs': ['11px', { lineHeight: '14px', fontWeight: '400' }],
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(8px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.4s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        'slide-in-right': 'slide-in-right 0.25s ease-out',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
  future: {
    hoverOnlyWhenSupported: true,
  },
};
