export const PERMISSION_DEFINITIONS = [
  { key: 'tickets.create', label: 'Créer des tickets' },
  { key: 'tickets.delete', label: 'Supprimer un ticket' },
  { key: 'tickets.bulkDelete', label: 'Supprimer des tickets en masse' },
  { key: 'tickets.assign', label: 'Assigner un ticket' },
  { key: 'tickets.approve', label: 'Approuver / rejeter un ticket' },
  { key: 'users.manage', label: 'Gérer les utilisateurs' },
  { key: 'teams.manage', label: 'Gérer les équipes' },
  { key: 'settings.manage', label: 'Gérer les paramètres (IA, emails, API, n8n, GLPI)' },
  { key: 'knowledge.manage', label: 'Gérer la base de connaissances' },
  { key: 'inbox.sync', label: 'Synchroniser la boîte mail' },
  { key: 'dashboard.view', label: 'Voir le tableau de bord' },
  { key: 'glpi.manage', label: 'Gérer la synchronisation GLPI' },
  { key: 'prompts.manage', label: 'Modifier les prompts IA' },
  { key: 'emaildrafts.manage', label: 'Approuver / rejeter les réponses email IA' },
  { key: 'automation.manage', label: "Gérer l'automatisation (auto-envoi, auto-approbation, synchro GLPI)" },
];
