-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "isMajorIncident" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "impactedSites" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "firstDetectedAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "lastDetectedAt" TIMESTAMP(3);
